import { z } from "zod";
import { adminRepository, taskRepository, workflowRepository } from "@nexus/database";
import { hashPassword, type RequestUser } from "./auth.service.js";

const organizationSchema = z.object({ name: z.string().trim().min(1), website: z.string().url().optional().nullable(), description: z.string().optional().nullable(), status: z.string().optional() });
const internalUserSchema = z.object({ firstName: z.string().trim().min(1), lastName: z.string().trim().min(1), email: z.string().email(), password: z.string().min(8).optional(), organizationId: z.string().uuid().optional().nullable(), roleIds: z.array(z.string().uuid()).optional(), active: z.boolean().optional() });
const organizationUserSchema = z.object({ firstName: z.string().trim().min(1), lastName: z.string().trim().min(1), email: z.string().email(), organizationId: z.string().uuid().optional().nullable(), role: z.string().optional().nullable() });
const messageSchema = z.object({ name: z.string().trim().min(1), content: z.string().optional().nullable(), active: z.boolean().optional() });

const isSuper = (user: RequestUser) => user.roles.includes("SUPER_ADMIN");
const scopedOrganization = (user: RequestUser) => isSuper(user) ? undefined : user.organizationId || "__none__";
const assertScope = (user: RequestUser, organizationId?: string | null) => { const scope = scopedOrganization(user); if (scope && scope !== organizationId) throw new Error("This record is outside your organization scope."); };
const safeInternal = (user: any) => { const { passwordHash: _passwordHash, ...safe } = user; return safe; };
const validateRoleAssignment = async (user: RequestUser, roleIds?: string[]) => { if (!roleIds?.length || isSuper(user)) return; const roles = await adminRepository.roles(); if (roles.some((role) => roleIds.includes(role.id) && role.name === "SUPER_ADMIN")) throw new Error("Only a super administrator can assign the SUPER_ADMIN role."); };
const pageQuery = z.object({ page: z.coerce.number().int().positive().default(1), pageSize: z.coerce.number().int().positive().max(100).default(25), search: z.string().trim().max(200).optional(), status: z.string().optional(), organizationId: z.string().uuid().optional(), assigneeId: z.string().uuid().optional(), templateId: z.string().uuid().optional(), role: z.string().optional(), active: z.enum(["true", "false"]).transform((value) => value === "true").optional(), overdue: z.enum(["true", "false"]).transform((value) => value === "true").optional() });

export const adminService = {
  overview: (user: RequestUser) => adminRepository.metrics(scopedOrganization(user)),
  organizations: (user: RequestUser, raw?: unknown) => adminRepository.pagedOrganizations(pageQuery.parse(raw || {}), scopedOrganization(user)),
  organization: async (user: RequestUser, id: string) => { assertScope(user, id); return adminRepository.organization(id); },
  createOrganization: async (user: RequestUser, raw: unknown) => { const input = organizationSchema.parse(raw); if (!isSuper(user) && user.organizationId) throw new Error("Only system administrators can create organizations."); const value = await adminRepository.createOrganization({ name: input.name, website: input.website, description: input.description, status: input.status }); await adminRepository.audit({ actorId: user.id, action: "ORGANIZATION_CREATED", entityType: "Organization", entityId: value.id }); return value; },
  updateOrganization: async (user: RequestUser, id: string, raw: unknown) => { assertScope(user, id); const input = organizationSchema.partial().parse(raw); const value = await adminRepository.updateOrganization(id, input); await adminRepository.audit({ actorId: user.id, action: "ORGANIZATION_UPDATED", entityType: "Organization", entityId: id }); return value; },
  users: async (user: RequestUser, raw?: unknown) => { const query = pageQuery.parse(raw || {}); const scope = scopedOrganization(user); return { internal: await adminRepository.pagedInternalUsers(query, scope), organization: await adminRepository.pagedOrganizationUsers(query, scope) }; },
  createInternalUser: async (user: RequestUser, raw: unknown) => { const input = internalUserSchema.parse(raw); assertScope(user, input.organizationId); await validateRoleAssignment(user, input.roleIds); const value = await adminRepository.createInternalUser({ firstName: input.firstName, lastName: input.lastName, email: input.email.toLowerCase(), passwordHash: input.password ? hashPassword(input.password) : null, active: input.active ?? true, organization: input.organizationId ? { connect: { id: input.organizationId } } : undefined }); if (input.roleIds?.length) await adminRepository.setUserRoles(value.id, input.roleIds); await adminRepository.audit({ actorId: user.id, action: "USER_CREATED", entityType: "InternalUser", entityId: value.id }); return safeInternal(value); },
  updateInternalUser: async (user: RequestUser, id: string, raw: unknown) => { const input = internalUserSchema.partial().parse(raw); const existing = await adminRepository.internalUsers(); const target = existing.find((item) => item.id === id); if (!target) return null; assertScope(user, target.organizationId); await validateRoleAssignment(user, input.roleIds); if (input.roleIds && target.roleAssignments.some((assignment) => assignment.role.name === "SUPER_ADMIN") && !isSuper(user)) throw new Error("Only a super administrator can change protected roles."); const value = await adminRepository.updateInternalUser(id, { firstName: input.firstName, lastName: input.lastName, email: input.email?.toLowerCase(), organization: input.organizationId === null ? { disconnect: true } : input.organizationId ? { connect: { id: input.organizationId } } : undefined, passwordHash: input.password ? hashPassword(input.password) : undefined, active: input.active }); if (input.roleIds) await adminRepository.setUserRoles(id, input.roleIds); await adminRepository.audit({ actorId: user.id, action: input.active === false ? "USER_DISABLED" : input.roleIds ? "ROLE_CHANGED" : "USER_UPDATED", entityType: "InternalUser", entityId: id }); return safeInternal(value); },
  organizationUsers: async (user: RequestUser) => { const scope = scopedOrganization(user); const values = await adminRepository.organizationUsers(); return scope ? values.filter((item) => item.organizationId === scope) : values; },
  createOrganizationUser: async (user: RequestUser, raw: unknown) => { const input = organizationUserSchema.parse(raw); assertScope(user, input.organizationId); return adminRepository.createOrganizationUser({ firstName: input.firstName, lastName: input.lastName, email: input.email.toLowerCase(), role: input.role, organization: input.organizationId ? { connect: { id: input.organizationId } } : undefined }); },
  updateOrganizationUser: async (user: RequestUser, id: string, raw: unknown) => { const input = organizationUserSchema.partial().parse(raw); const users = await adminRepository.organizationUsers(); const target = users.find((item) => item.id === id); if (!target) return null; assertScope(user, target.organizationId); return adminRepository.updateOrganizationUser(id, { firstName: input.firstName, lastName: input.lastName, email: input.email?.toLowerCase(), role: input.role, organization: input.organizationId === null ? { disconnect: true } : input.organizationId ? { connect: { id: input.organizationId } } : undefined }); },
  roles: () => adminRepository.roles(),
  permissions: () => adminRepository.permissions(),
  updateRole: async (user: RequestUser, roleId: string, permissionIds: string[]) => { if (!isSuper(user)) throw new Error("Only a super administrator can edit permissions."); const value = await adminRepository.updateRolePermissions(roleId, permissionIds); await adminRepository.audit({ actorId: user.id, action: "ROLE_PERMISSIONS_CHANGED", entityType: "Role", entityId: roleId }); return value; },
  messageTemplates: () => adminRepository.messageTemplates(),
  createMessageTemplate: async (user: RequestUser, raw: unknown) => { const input = messageSchema.parse(raw); const value = await adminRepository.createMessageTemplate(input); await adminRepository.audit({ actorId: user.id, action: "MESSAGE_TEMPLATE_CREATED", entityType: "MessageTemplate", entityId: value.id }); return value; },
  updateMessageTemplate: async (user: RequestUser, id: string, raw: unknown) => { const input = messageSchema.partial().parse(raw); const value = await adminRepository.updateMessageTemplate(id, input); await adminRepository.audit({ actorId: user.id, action: "MESSAGE_TEMPLATE_UPDATED", entityType: "MessageTemplate", entityId: id }); return value; },
  tasks: async (user: RequestUser, raw?: unknown) => adminRepository.pagedTasks(pageQuery.parse(raw || {}), scopedOrganization(user)),
  workflows: async (user: RequestUser, raw?: unknown) => adminRepository.pagedWorkflows(pageQuery.parse(raw || {}), scopedOrganization(user)),
  auditLogs: (raw?: unknown) => { const query = z.object({ action: z.string().optional(), entityType: z.string().optional(), actorId: z.string().uuid().optional(), page: z.coerce.number().int().positive().default(1), pageSize: z.coerce.number().int().positive().max(100).default(50) }).parse(raw || {}); return adminRepository.auditLogs(query); },
};
