import { prisma } from "./client.js";
import type { Prisma } from "@prisma/client";

export const organizationRepository = {
  list: (organizationId?: string) => prisma.organization.findMany({ where: organizationId ? { id: organizationId } : undefined, orderBy: { createdAt: "desc" } }),
  create: (data: { name: string; website?: string; description?: string; status?: string }) => prisma.organization.create({ data }),
};

export const userRepository = {
  list: (organizationId?: string) => prisma.user.findMany({ where: organizationId ? { organizationId } : undefined, include: { organization: true }, orderBy: { createdAt: "desc" } }),
  create: (data: { firstName: string; lastName: string; email: string; organizationId?: string; phone?: string }) => prisma.user.create({ data }),
};

export const taskTemplateRepository = {
  list: () => prisma.taskTemplate.findMany({ include: { message: { include: { messageTemplate: true } }, condition: { include: { requiredFields: true } }, defaultAssignee: true }, orderBy: { updatedAt: "desc" } }),
  get: (id: string) => prisma.taskTemplate.findUnique({ where: { id }, include: { message: { include: { messageTemplate: true } }, condition: { include: { requiredFields: true } }, defaultAssignee: true } }),
  create: (data: Prisma.TaskTemplateCreateInput) => prisma.taskTemplate.create({ data, include: { message: { include: { messageTemplate: true } }, condition: { include: { requiredFields: true } }, defaultAssignee: true } }),
  update: (id: string, data: Prisma.TaskTemplateUpdateInput) => prisma.taskTemplate.update({ where: { id }, data, include: { message: { include: { messageTemplate: true } }, condition: { include: { requiredFields: true } }, defaultAssignee: true } }),
  deleteMessage: (taskTemplateId: string) => prisma.taskTemplateMessage.deleteMany({ where: { taskTemplateId } }),
  deactivate: (id: string) => prisma.taskTemplate.update({ where: { id }, data: { active: false, availableForTasks: false, availableForWorkflows: false } }),
  internalUsers: () => prisma.internalUser.findMany({ where: { active: true }, orderBy: [{ firstName: "asc" }, { lastName: "asc" }] }),
  messageTemplates: () => prisma.messageTemplate.findMany({ where: { active: true }, orderBy: { name: "asc" } }),
};

export const taskRepository = {
  list: (organizationId?: string) => prisma.task.findMany({ where: organizationId ? { organizationId } : undefined, include: { taskTemplate: { include: { condition: { include: { requiredFields: true } } } }, organization: true, assignee: true, creator: true, requiredData: { include: { requiredField: true } }, comments: { include: { author: true }, orderBy: { createdAt: "asc" } }, statusHistory: { include: { changer: true }, orderBy: { changedAt: "asc" } }, workflowStep: { include: { workflow: true, step: { include: { workflowTemplate: true } } } } }, orderBy: { createdAt: "desc" } }),
  get: (id: string, organizationId?: string) => prisma.task.findFirst({ where: { id, ...(organizationId ? { organizationId } : {}) }, include: { taskTemplate: { include: { condition: { include: { requiredFields: true } } } }, organization: true, assignee: true, creator: true, requiredData: { include: { requiredField: true } }, comments: { include: { author: true }, orderBy: { createdAt: "asc" } }, statusHistory: { include: { changer: true }, orderBy: { changedAt: "asc" } }, workflowStep: { include: { workflow: true, step: { include: { workflowTemplate: true } } } } } }),
  create: (data: Prisma.TaskCreateInput) => prisma.task.create({ data, include: { taskTemplate: { include: { condition: { include: { requiredFields: true } } } }, organization: true, assignee: true, creator: true, requiredData: { include: { requiredField: true } }, comments: { include: { author: true } }, statusHistory: { include: { changer: true } }, workflowStep: { include: { workflow: true, step: { include: { workflowTemplate: true } } } } } }),
  update: (id: string, data: Prisma.TaskUpdateInput) => prisma.task.update({ where: { id }, data, include: { taskTemplate: { include: { condition: { include: { requiredFields: true } } } }, organization: true, assignee: true, creator: true, requiredData: { include: { requiredField: true } }, comments: { include: { author: true }, orderBy: { createdAt: "asc" } }, statusHistory: { include: { changer: true }, orderBy: { changedAt: "asc" } }, workflowStep: { include: { workflow: true, step: { include: { workflowTemplate: true } } } } } }),
  internalUsers: () => prisma.internalUser.findMany({ where: { active: true }, orderBy: [{ firstName: "asc" }, { lastName: "asc" }] }),
  templates: () => prisma.taskTemplate.findMany({ where: { active: true, availableForTasks: true }, include: { condition: { include: { requiredFields: true } } }, orderBy: { categoryName: "asc" } }),
  workflows: () => prisma.workflow.findMany({ include: { template: true }, orderBy: { createdAt: "desc" } }),
  organizations: () => prisma.organization.findMany({ orderBy: { name: "asc" } }),
  statusHistory: (taskId: string, data: Prisma.TaskStatusHistoryCreateWithoutTaskInput, transaction: Prisma.TransactionClient = prisma) => transaction.taskStatusHistory.create({ data: { ...data, task: { connect: { id: taskId } } }, include: { changer: true } }),
  addComment: (taskId: string, data: { comment: string; authorId?: string }, transaction: Prisma.TransactionClient = prisma) => transaction.taskComment.create({ data: { comment: data.comment, author: data.authorId ? { connect: { id: data.authorId } } : undefined, task: { connect: { id: taskId } } }, include: { author: true } }),
  transaction: <T>(callback: (transaction: Prisma.TransactionClient) => Promise<T>) => prisma.$transaction(callback),
};

export const workflowTemplateRepository = {
  list: () => prisma.workflowTemplate.findMany({ include: { creator: true, steps: { include: { taskTemplate: true, outcomes: { include: { targetStep: true }, orderBy: { kind: "asc" } } }, orderBy: { stepOrder: "asc" } } }, orderBy: { updatedAt: "desc" } }),
  get: (id: string) => prisma.workflowTemplate.findUnique({ where: { id }, include: { creator: true, steps: { include: { taskTemplate: { include: { condition: { include: { requiredFields: true } } } }, outcomes: { include: { targetStep: true }, orderBy: { kind: "asc" } } }, orderBy: { stepOrder: "asc" } } } }),
  create: (data: Prisma.WorkflowTemplateCreateInput) => prisma.workflowTemplate.create({ data, include: { steps: { include: { taskTemplate: true, outcomes: { include: { targetStep: true } } }, orderBy: { stepOrder: "asc" } } } }),
  update: (id: string, data: Prisma.WorkflowTemplateUpdateInput) => prisma.workflowTemplate.update({ where: { id }, data, include: { steps: { include: { taskTemplate: true, outcomes: { include: { targetStep: true } } }, orderBy: { stepOrder: "asc" } } } }),
  taskTemplates: () => prisma.taskTemplate.findMany({ where: { active: true, availableForWorkflows: true }, include: { condition: { include: { requiredFields: true } } }, orderBy: { categoryName: "asc" } }),
  internalUsers: () => prisma.internalUser.findMany({ where: { active: true }, orderBy: [{ firstName: "asc" }, { lastName: "asc" }] }),
};

export const workflowRepository = {
  list: (organizationId?: string) => prisma.workflow.findMany({ where: organizationId ? { organizationId } : undefined, include: { organization: true, template: true, currentStep: { include: { step: true, task: true } }, steps: { include: { step: true, task: true }, orderBy: { createdAt: "asc" } }, statusHistory: { orderBy: { changedAt: "asc" } } }, orderBy: { createdAt: "desc" } }),
  get: (id: string, organizationId?: string) => prisma.workflow.findFirst({ where: { id, ...(organizationId ? { organizationId } : {}) }, include: { organization: true, template: { include: { steps: { include: { taskTemplate: true, outcomes: { include: { targetStep: true } } }, orderBy: { stepOrder: "asc" } } } }, currentStep: { include: { step: true, task: true } }, steps: { include: { step: { include: { taskTemplate: true, outcomes: { include: { targetStep: true } } } }, task: true }, orderBy: { createdAt: "asc" } }, statusHistory: { include: { changer: true }, orderBy: { changedAt: "asc" } } } }),
  create: (data: { name: string; description?: string; organizationId?: string; templateId?: string; createdBy?: string }) => prisma.workflow.create({ data }),
  organizations: () => prisma.organization.findMany({ orderBy: { name: "asc" } }),
  transaction: <T>(callback: (transaction: Prisma.TransactionClient) => Promise<T>) => prisma.$transaction(callback),
};

export const authRepository = {
  userByEmail: (email: string) => prisma.internalUser.findUnique({ where: { email: email.toLowerCase() }, include: { organization: true, roleAssignments: { include: { role: { include: { permissions: { include: { permission: true } } } } } } } }),
  userById: (id: string) => prisma.internalUser.findUnique({ where: { id }, include: { organization: true, roleAssignments: { include: { role: { include: { permissions: { include: { permission: true } } } } } } } }),
  createSession: (data: { tokenHash: string; userId: string; expiresAt: Date }) => prisma.authSession.create({ data }),
  session: (tokenHash: string) => prisma.authSession.findUnique({ where: { tokenHash }, include: { user: { include: { organization: true, roleAssignments: { include: { role: { include: { permissions: { include: { permission: true } } } } } } } } } }),
  touchSession: (id: string) => prisma.authSession.update({ where: { id }, data: { lastSeenAt: new Date() } }),
  deleteSession: (tokenHash: string) => prisma.authSession.deleteMany({ where: { tokenHash } }),
  updateLogin: (id: string) => prisma.internalUser.update({ where: { id }, data: { lastLoginAt: new Date() } }),
  audit: (data: { actorId?: string; action: string; entityType: string; entityId?: string; metadata?: object }) => prisma.auditLog.create({ data: { actorId: data.actorId, action: data.action, entityType: data.entityType, entityId: data.entityId, metadata: data.metadata } }),
};

export const adminRepository = {
  pagedOrganizations: async (query: { page: number; pageSize: number; search?: string; status?: string }, organizationId?: string) => { const where = { ...(organizationId ? { id: organizationId } : {}), ...(query.status ? { status: query.status } : {}), ...(query.search ? { name: { contains: query.search, mode: "insensitive" as const } } : {}) }; const [items, total] = await Promise.all([prisma.organization.findMany({ where, include: { _count: { select: { users: true, tasks: true, workflows: true } } }, orderBy: { updatedAt: "desc" }, skip: (query.page - 1) * query.pageSize, take: query.pageSize }), prisma.organization.count({ where })]); return { items, page: query.page, pageSize: query.pageSize, total, totalPages: Math.ceil(total / query.pageSize) }; },
  pagedInternalUsers: async (query: { page: number; pageSize: number; search?: string; organizationId?: string; active?: boolean; role?: string }, scope?: string) => { const where = { ...(scope ? { organizationId: scope } : {}), ...(query.organizationId ? { organizationId: query.organizationId } : {}), ...(query.active === undefined ? {} : { active: query.active }), ...(query.search ? { OR: [{ firstName: { contains: query.search, mode: "insensitive" as const } }, { lastName: { contains: query.search, mode: "insensitive" as const } }, { email: { contains: query.search, mode: "insensitive" as const } }] } : {}), ...(query.role ? { roleAssignments: { some: { role: { name: query.role } } } } : {}) }; const [items, total] = await Promise.all([prisma.internalUser.findMany({ where, include: { organization: true, roleAssignments: { include: { role: true } } }, orderBy: { createdAt: "desc" }, skip: (query.page - 1) * query.pageSize, take: query.pageSize }), prisma.internalUser.count({ where })]); return { items: items.map(({ passwordHash: _passwordHash, ...item }) => item), page: query.page, pageSize: query.pageSize, total, totalPages: Math.ceil(total / query.pageSize) }; },
  pagedOrganizationUsers: async (query: { page: number; pageSize: number; search?: string; organizationId?: string }, scope?: string) => { const where = { ...(scope ? { organizationId: scope } : {}), ...(query.organizationId ? { organizationId: query.organizationId } : {}), ...(query.search ? { OR: [{ firstName: { contains: query.search, mode: "insensitive" as const } }, { lastName: { contains: query.search, mode: "insensitive" as const } }, { email: { contains: query.search, mode: "insensitive" as const } }] } : {}) }; const [items, total] = await Promise.all([prisma.user.findMany({ where, include: { organization: true }, orderBy: { createdAt: "desc" }, skip: (query.page - 1) * query.pageSize, take: query.pageSize }), prisma.user.count({ where })]); return { items, page: query.page, pageSize: query.pageSize, total, totalPages: Math.ceil(total / query.pageSize) }; },
  pagedTasks: async (query: { page: number; pageSize: number; search?: string; status?: string; organizationId?: string; assigneeId?: string; overdue?: boolean }, scope?: string) => { const where = { ...(scope ? { organizationId: scope } : {}), ...(query.organizationId ? { organizationId: query.organizationId } : {}), ...(query.status ? { status: query.status as any } : {}), ...(query.assigneeId ? { assigneeId: query.assigneeId } : {}), ...(query.overdue ? { dueAt: { lt: new Date() }, status: { not: "COMPLETE" } } : {}), ...(query.search ? { OR: [{ title: { contains: query.search, mode: "insensitive" as const } }, { description: { contains: query.search, mode: "insensitive" as const } }] } : {}) }; const include = { taskTemplate: true, organization: true, assignee: true, workflowStep: { include: { workflow: true } } }; const [items, total] = await Promise.all([prisma.task.findMany({ where, include, orderBy: { createdAt: "desc" }, skip: (query.page - 1) * query.pageSize, take: query.pageSize }), prisma.task.count({ where })]); return { items, page: query.page, pageSize: query.pageSize, total, totalPages: Math.ceil(total / query.pageSize) }; },
  pagedWorkflows: async (query: { page: number; pageSize: number; search?: string; status?: string; organizationId?: string; templateId?: string }, scope?: string) => { const where = { ...(scope ? { organizationId: scope } : {}), ...(query.organizationId ? { organizationId: query.organizationId } : {}), ...(query.templateId ? { templateId: query.templateId } : {}), ...(query.status ? { status: query.status as any } : {}), ...(query.search ? { name: { contains: query.search, mode: "insensitive" as const } } : {}) }; const include = { organization: true, template: true, currentStep: { include: { step: true, task: true } } }; const [items, total] = await Promise.all([prisma.workflow.findMany({ where, include, orderBy: { createdAt: "desc" }, skip: (query.page - 1) * query.pageSize, take: query.pageSize }), prisma.workflow.count({ where })]); return { items, page: query.page, pageSize: query.pageSize, total, totalPages: Math.ceil(total / query.pageSize) }; },
  metrics: async (organizationId?: string) => { const scope = organizationId ? { organizationId } : {}; const [organizations, activeOrganizations, internalUsers, organizationUsers, activeUsers, activeTasks, overdueTasks, pendingTasks, inProgressTasks, completedTasks, workflowTemplates, runningWorkflows, completedWorkflows, failedWorkflows, messageTemplates, recentActivity, recentUsers, recentTasks] = await Promise.all([prisma.organization.count({ where: organizationId ? { id: organizationId } : undefined }), prisma.organization.count({ where: { ...scope, status: { not: "INACTIVE" } } }), prisma.internalUser.count({ where: { active: true, ...scope } }), prisma.user.count({ where: organizationId ? { organizationId } : undefined }), prisma.user.count({ where: { ...(organizationId ? { organizationId } : {}), portalAccessStatus: "ACTIVE" } }), prisma.task.count({ where: { ...scope, status: { not: "COMPLETE" } } }), prisma.task.count({ where: { ...scope, status: { not: "COMPLETE" }, dueAt: { lt: new Date() } } }), prisma.task.count({ where: { ...scope, status: { in: ["BACKLOG", "PENDING"] } } }), prisma.task.count({ where: { ...scope, status: "IN_PROGRESS" } }), prisma.task.count({ where: { ...scope, status: "COMPLETE" } }), prisma.workflowTemplate.count({ where: { active: true } }), prisma.workflow.count({ where: { ...scope, status: "IN_PROGRESS" } }), prisma.workflow.count({ where: { ...scope, status: "COMPLETE" } }), prisma.workflow.count({ where: { ...scope, status: "FAILED" } }), prisma.messageTemplate.count({ where: { active: true } }), prisma.auditLog.findMany({ include: { actor: true }, orderBy: { createdAt: "desc" }, take: 8 }), prisma.internalUser.findMany({ where: { active: true, ...scope }, orderBy: { createdAt: "desc" }, take: 8, select: { id: true, firstName: true, lastName: true, email: true, createdAt: true, lastLoginAt: true, organization: { select: { name: true } } } }), prisma.task.findMany({ where: scope, include: { organization: true, assignee: true, taskTemplate: true }, orderBy: { createdAt: "desc" }, take: 8 })]); return { organizations, activeOrganizations, internalUsers, organizationUsers, activeUsers, activeTasks, overdueTasks, pendingTasks, inProgressTasks, completedTasks, taskTemplates: await prisma.taskTemplate.count({ where: { active: true } }), workflowTemplates, runningWorkflows, completedWorkflows, failedWorkflows, messageTemplates, recentActivity, recentUsers, recentTasks }; },
  organizations: (organizationId?: string) => prisma.organization.findMany({ where: organizationId ? { id: organizationId } : undefined, include: { _count: { select: { users: true, tasks: true, workflows: true } } }, orderBy: { updatedAt: "desc" } }),
  organization: (id: string) => prisma.organization.findUnique({ where: { id }, include: { users: true, tasks: { include: { taskTemplate: true, assignee: true }, orderBy: { createdAt: "desc" }, take: 20 }, workflows: { include: { template: true }, orderBy: { createdAt: "desc" }, take: 20 }, statusHistory: { orderBy: { changedAt: "desc" }, take: 20 } } }),
  createOrganization: (data: Prisma.OrganizationCreateInput) => prisma.organization.create({ data }),
  updateOrganization: (id: string, data: Prisma.OrganizationUpdateInput) => prisma.organization.update({ where: { id }, data }),
  internalUsers: () => prisma.internalUser.findMany({ include: { organization: true, roleAssignments: { include: { role: true } } }, orderBy: { createdAt: "desc" } }),
  organizationUsers: () => prisma.user.findMany({ include: { organization: true }, orderBy: { createdAt: "desc" } }),
  createInternalUser: (data: Prisma.InternalUserCreateInput) => prisma.internalUser.create({ data }),
  updateInternalUser: (id: string, data: Prisma.InternalUserUpdateInput) => prisma.internalUser.update({ where: { id }, data }),
  setUserRoles: (userId: string, roleIds: string[]) => prisma.$transaction(async (transaction) => { await transaction.internalUserRole.deleteMany({ where: { userId } }); if (roleIds.length) await transaction.internalUserRole.createMany({ data: roleIds.map((roleId) => ({ userId, roleId })) }); return transaction.internalUser.findUnique({ where: { id: userId }, include: { roleAssignments: { include: { role: true } } } }); }),
  createOrganizationUser: (data: Prisma.UserCreateInput) => prisma.user.create({ data }),
  updateOrganizationUser: (id: string, data: Prisma.UserUpdateInput) => prisma.user.update({ where: { id }, data }),
  roles: () => prisma.role.findMany({ include: { permissions: { include: { permission: true } }, _count: { select: { assignments: true } } }, orderBy: { name: "asc" } }),
  updateRolePermissions: (roleId: string, permissionIds: string[]) => prisma.$transaction(async (transaction) => { await transaction.rolePermission.deleteMany({ where: { roleId } }); if (permissionIds.length) await transaction.rolePermission.createMany({ data: permissionIds.map((permissionId) => ({ roleId, permissionId })) }); return transaction.role.findUnique({ where: { id: roleId }, include: { permissions: { include: { permission: true } } } }); }),
  permissions: () => prisma.permission.findMany({ orderBy: { key: "asc" } }),
  messageTemplates: () => prisma.messageTemplate.findMany({ orderBy: { updatedAt: "desc" } }),
  createMessageTemplate: (data: Prisma.MessageTemplateCreateInput) => prisma.messageTemplate.create({ data }),
  updateMessageTemplate: (id: string, data: Prisma.MessageTemplateUpdateInput) => prisma.messageTemplate.update({ where: { id }, data }),
  audit: (data: { actorId?: string; action: string; entityType: string; entityId?: string; metadata?: object }) => prisma.auditLog.create({ data: { actorId: data.actorId, action: data.action, entityType: data.entityType, entityId: data.entityId, metadata: data.metadata } }),
  auditLogs: async (query: { action?: string; entityType?: string; actorId?: string; page: number; pageSize: number }) => { const where = { action: query.action ? { contains: query.action, mode: "insensitive" as const } : undefined, entityType: query.entityType ? { equals: query.entityType } : undefined, actorId: query.actorId }; const [items, total] = await Promise.all([prisma.auditLog.findMany({ where, include: { actor: true }, orderBy: { createdAt: "desc" }, skip: (query.page - 1) * query.pageSize, take: query.pageSize }), prisma.auditLog.count({ where })]); return { items, page: query.page, pageSize: query.pageSize, total, totalPages: Math.ceil(total / query.pageSize) }; },
};